name: pi-gen-build

on:
  workflow_dispatch:
  release:
    type: [created, published, released]
#  push:
#    branches: [ "main-dev" ]
#  pull_request:
#    branches: [ "main-dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

#      - name: Docker Setup Docker
#        uses: docker/setup-docker-action@v4.7.0

      - name: Install pi-gen dependencies
        run: |
          sudo apt update && 
          sudo apt -y install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools e2fsprogs libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc gpg pigz xxd arch-test bmap-tools kmod

      - name: Run pi-gen auto.sh build script
        run: cd pi-gen-sources && sudo bash ./auto.sh

      # via https://github.com/RPi-Distro/pi-gen/pull/786
      - name: Get Image Name
        id: imagefile
        run: |
          echo "---"
          echo $PWD
          ls
          echo "---"
          cd pi-gen-sources/pi-gen/deploy
          echo $PWD
          ls
          echo "---"
          IMAGE_FILE=$(ls *.zip)
          echo "Found image file: $IMAGE_FILE"
          echo "---"
          echo "imagefile=$IMAGE_FILE" >> $GITHUB_OUTPUT
          NOW=$(date +"%Y-%m-%d-%H%M")
          IMAGE=TeslaUSB-$NOW-${GITHUB_REF##*/}
          echo "name=$IMAGE.zip"  >> $GITHUB_OUTPUT

      # The image now exists in deploy/.
      # Make the artifact available from the action.
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.imagefile.outputs.name }}
          path: pi-gen-sources/pi-gen/deploy/${{ steps.imagefile.outputs.imagefile }}